spring:
  application:
    name: Augus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/Augus?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  security:
    user:
      password: "123456"
    csrf:
      enabled: false

  data:
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 1000
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    max-connections: 50000

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn
    com.egzosn: debug

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: cuibing-yangpanting-2017/12/14-10:41pm
  # 令牌有效期（默认30分钟）
  expireTime: 3600000

app:
  secretKey: cui-bing&yang-panting-2017/12/14

jwt:
  secret: mySecretKey
  expiration: 3600000





